### ISSUE TITLE
UX Issue on Private smallcases page

### ISSUE THREAD

**Issue by yashraj2312** [smallcase/react-native-smallcase-gateway#1]
Hey team, I know this ain't the right repository to create this issue but I can't see any other relevant repo for this bug.

On your web app, In the private smallcases pages "Request for an invite" button doesn't trigger your mailer system backend properly. It does redirects to the automated mail of subscribing to the smallcase but in your backend, the invite code doesn't get triggered to be sent to the user. 

THIS SEEMS TO BE MAJOR UX ISSUE. I myself have waited for more than 6 days to get an invite but haven't received any.
There's a workaround for this though. We need to log out and open the page in incognito mode and then complete the payment process in order to subscribe to that smallcase. 

"Request for invite" program is gimmicky and became a thing of the past. You folks have already established your brand and no more need to build the hype. 

P.S - Apologies for hasty english. ( I have a sprint review meeting coming up soon otherwise I would have written it in a proper markdown format). 
_HMU if you want me to explain the bug in a more clear manner or reproduce it._

<img width="1440" alt="Screenshot 2021-07-14 at 4 13 41 PM" src="https://user-images.githubusercontent.com/48771399/125609348-a5d088be-1365-4274-8ca9-1e64d8329be6.png">
I'm talking about this Blue request for invite button.

**Comment by LonelyCpp** [comment]
Hey we have noted this issue and will look into it. 

If you need any help regarding this or general feedback, please contact us through help@smallcase.com

thank you!
